---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - operator.molido.com
  resources:
  - databacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.molido.com
  resources:
  - databacks/finalizers
  verbs:
  - update
- apiGroups:
  - operator.molido.com
  resources:
  - databacks/status
  verbs:
  - get
  - patch
  - update
