apiVersion: operator.molido.com/v1beta1
kind: Databack
metadata:
  labels:
    app.kubernetes.io/name: databack-operator
    app.kubernetes.io/managed-by: kustomize
  name: databack-sample
spec:
  enable: true
  startTime: "10:21"
  period: 2
  origin:
    host: "mysql-service.default.svc.cluster.local"
    # host: "10.43.188.50"
    port: 3306
    username: "root"
    password: "MyRootPass123"
  destination:
    endpoint: ""
    accessKey: ""
    accessSecret: ""
    buketName: ""
